// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD208oBco5Uha3UN1Uk34SENUg7pnEM58',
    appId: '1:380558064001:android:56ee716b03e95ee2459080',
    messagingSenderId: '380558064001',
    projectId: 'csi464lab6',
    storageBucket: 'csi464lab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2yMWyICAKjlGirwuYewwdJI4oFlg7rUY',
    appId: '1:380558064001:ios:001502ca1a14569a459080',
    messagingSenderId: '380558064001',
    projectId: 'csi464lab6',
    storageBucket: 'csi464lab6.appspot.com',
    iosClientId: '380558064001-ai4q48dgkt96vl0r8vqglvi327tc0k98.apps.googleusercontent.com',
    iosBundleId: 'ios',
  );
}
